apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: commafeed
resources:
  - secrets.yaml
  - configmap.yaml
  - service.yaml
  - deployment.yaml
  - httproute.yaml
  - networkpolicy.yaml
