---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 30m
  timeout: 15m
  chartRef:
    kind: OCIRepository
    name: cilium
    # namespace is not required here
  valuesFrom:
    - kind: ConfigMap
      name: cilium-values
  # dependsOn:
  #   - name: gateway-api
  #     namespace: flux-system
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  driftDetection:
    mode: enabled
