---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secrets
  namespace: commafeed
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgChOaEQqVF2Vhekz/i6ZeSSBb3uKP62spcj8FdsiXIZKIvw1lQUCHuip1lnYOUanTn2lB9CEVjshDV2BqiavvLpkrTXhhUZNE9WagBhEqH5yByzFeZimYweBp0XcCpdwEJZVNqupATfLhM3/PIJ9SKFCxkp5/JusNg07n/UzEpnu36P+iFRRAwMJqlTS8ykq4YrvoWpS7/3xb1CFEbiMu/ld3UdvamTpjg/tA3s0XzF0sr8YpJ9ADlSDHfSHQvg32ibiQFE5uj7AG9gUDhkewIiZucQ9I+TOOfXvNYVqUr24hOLZSKlmnCph6OMY+4860pa4EhxUSO5h2Lugzed2dcZTNj33s8BsulKIXU0ZsDgBogKuq81KoFZiJ6pdPVg8ya9cBWJUzI5HeYvPt+89P2Lm80TN6giW2+qLeZ0FH7N4Ax2ifB3n1rVojVjrunNhAf8O9HkIdhc9r/6ukhLaluCFdIHMWzjFCVsiyp5kw1kD7FyDxK++dOhT4unWFrndl7WPCTNGvZJyh1G9z1HLCxixG8pgCdxGYspnI5S+iObACh0k5as0Sa5em83YGQXuA+sXx3C+jdE7XtuQ+1ODmgXJydYj+Pq//RucKCJdzJSOsinsQFIhLS9tjAZaPEUjDZyopjj+utdFU+vKS6rAqcGConbghph8ObHVW/FD7APKVptVQi4SWH1Pb4qXc4xb7oXFOr/3kZLvEg2bLs=
    POSTGRES_USER: AgBerkWpD8EaWSepLpXikTwZb0ygiJGVYM1djoSTRXJshoMx33Pd/7Shf7Jsm+YkCjoCls0j6JhTOVCpphY+WeERQl1kSvES6yqUyD/2hH8b09FP10ktIdKoRBVUDm1Pu8WEvHNtLJ7Bq3kqso/jdvykMuWgbeyaaRJbmkesmli2nfzgP6mQ5RcI1so+N7HuGHCBix0FaZonFtD8EBV6NaTG/l6Kt53RlN/BXR/Otfi6tlFfH7eQ5+7DWWmm/YuD+CBe6RPIHu0yOOPl5WEYL+wP5xgf3CZHBheM2AYLBIOBHMoGkfmg+5rTzrZkgY3fygEhoSESDZm+3rR65y/UZoQpHeQREwYBy9A2n5g7j8V0qczYmmu6TuXOP7wrl2ggGIG+BqZk0xGm8ruR1b/mE38TtZg1nJKg9jGEVsG2QtuBaoHLaoJsMi6/IZ+XLc5zfmaFcqwo/5o0nmlFa69u5GijAjC2TVCVX2EWq5/YSkquy865cUTgU76CTuEe9FxVXqjmbsvxi7B+HrONQwYqpWjOECdfZw2sYYZhFZZOsdeKxLmBZ11oBXBiKzAbhTBXSOLa7v4XUc46fJf98U9ezlVAYNz7JCcp2bc56AIj61Vig2LynV6aW/VdT2CeozOt1EDvk96+Q7bV1A+Gynmzd8zeIVTn+ivxBiRMOcwNVPLs2TZeFET82A7MtbVuvr4ZF2kvtVl780sc
  template:
    metadata:
      name: postgres-secrets
      namespace: commafeed
