---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secrets
  namespace: commafeed
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgB0Ne+r6hd+BGuGYeWJBVQfMtzSNKVWrSX0ZVCwsaXmEp0a/SmYFFjRDs9KZHTRI77yNtnfSPuSRww7FFvXzZvEZV1w2BP63PdbZ+PHaUh/Xla12BdksXf2lxd6yW709darI8UchFYGwpGxrJhYNO6u1yJVHyEPw5kujW3D3ndLIVT+How7XUYkI7WJ9ogKwNYnUnFVviqAy0l+twwsVUbhZ4vDqRVMnudWIxOI6aAy131+cYQrXqRb6eyMrM1O5+fzjsscN2m1AzsrE7E1V51Vq35PoZljQyNRQAmuu+2jy8KGN5mN7B4fwBkRSnHOF2XyK77Op/iuJuivI2Vhn6UVgOUexMvZuee8XP/Y4lu2fy24F2bt6epFjkQP+dVbkUnhEBEwWXqxSSbMUB4IjFn5ti9kdw7Pbc5LXZU2/THTHabCxQw2z4h16RJ2rzWCuVISm+TQBVGDGaejFFQ6Vm08CwHCT4D506kiNR8QFS/kbh2Kg1kPwFuYsE9DJs8pTi4Xs1ry81yTfdpzVPbXaNdbnBGZJghkaP8GRoL4/DB4xymODJBA+ml9mdpUxrUtDFTCMP5fkIerZfWoltXUUXlP+EsKvegZCQ9enXScmS+JKAeBmIjETEn3THSj6CopkB1/cuxpcnl9oVgrLi+9byhzDJSRm3H2v3KCWXd+kCfge3ovuB5yPEGeFc2XIkWOSt2Ec/SDxZj6ScuqxOY=
    POSTGRES_USER: AgCpemW53vDoYgmLylTyJlXVSk2FkfT2dXxEnuHxFlm9qztwX1ExgKqmGlDak7yYw0COUGNC1tQsVxtZTdNrl77DJ7MBCGe33G80YzYtFan16Q5C9OCB495WpbY9zwArskCBFzy+yZ86gSkJ5A8CTinqzVCzo/9XJqBwQQPp8BnUftvnyjvD+jY+ffN4clm3iAW3fe84UMKVgCD9R4fi7pZzi3Eo4+JI2sUSuIviQgPVtv30byfw6MZTa/mSlKbTtHvQFtZm1sCKmTWgyNJTEm2rDbMoRHh4NWwWRdsKlXIL5HlviAXKgWHv3pomojNx2nhdVn+TbeDsmEoLt2KLjPdEpgcyf5MExi72fvMKAeDKqE0DlLACWyX8gUl5cjuiCALcqiGMiKK0wNaXeOnN6pqhuSgZJaMsgCi1wEdohHVvrwFbv2rfA2S0sC8v+BmpKLCy64iFAPVHAVM+T1bBoSfly+p010HCpq/Mlw+rZTICx/iKAnXxx/K7t1j0bfE1DnE+UALymvLBJjWTcdFsHpChy5/Q0S9oSqLw3syD8F63bsCDKRdO14sEvQAtVmPCtks9PNSqKlsqd4lg2bwlhj5euEzEWcGox+5EaK/GrckRPtRAJW7t3jqGvACyKtrJHvYulfV6lqsnD87VQ9A4VdHP7qq1HnAjcxsnrk3r1sGnufU/JvXg1JXptjXpc+SCuG6aRlDbjMTY
  template:
    metadata:
      name: postgres-secrets
      namespace: commafeed
