---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secrets
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgDJIvDY3A+UjHVCLj6d4y4gJXmYwV2LgzwWNWXH7KA32tt+It4RVWlzj462FO8Yimq1JngROAkdmrD9egDxhwMwIuLT6tDPUbpNgTaXBs8uRcx95sLcV09vQ7evTLtjvLhvI/fgGHeMMn7prk/UE3wCULp9luTQFrceN1QB817EywkVVbzmp9bxUOEhOPpaJKImsrQLMmjzsWDWjLckPXeVINaHxhAGbw+nFRBTmbIhcb9FVYJ2d9ZyBLjxfxYG+qiIWGyEoqPUeMlnnMu5Kd6Z6DC7GCLQ8VoOobvxFuWzIMTZaQnjg/Q9eVLdsrV1crW2VwvpLZguAEAzQbJ9F1Pn/+do7lvYzXOTixkCu+kRc3AvLmwD8YTO2oHpm/MqjJMFZgV6MZtYmUQifUYi+dPyb9x0WFov1/S4rKgLfHmtewQSi8oKZ1deVc4E2pj8TuwQFh2dbzD9kXMoHM/USoI6OiO/3i1bxbUjvOlh2Tf2Ie7vJ5X0adLti6l2JUoGSuheKQrxzLDT7KxFpv+QsUUZH7vqafaXG1CfrbhbZum2wn+igtuSBW46jGyt6Tjm9XKJ+Ucx3b3chasJeUsgzauB+TFbDK8tchs4/IOlBRiMfZlXMirlEu/QE2nTNp09oDLlh0grZYZNCVDv7DCN7vUmr3yahI8MfDoHdWApVPiwaJDKdTS7H28spdmqtRRJRZvkfDyXsPVpInhb+js=
  template:
    metadata:
      name: grafana-secrets
      namespace: monitoring
