---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secrets
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgDi8WoJZCozpUcS4+qSZoaC4gX3XCINoaJ+o8r0eo+MBDk+uxJiNowbTplaLUFLv/UhEjk7bNoclGUd0CvhIk1zlvbc5UvSKXMHJt3PSeSqkted77TQ6g/IRzh/cBi6FzMpZOd2ji9xr3LI7XxCS3nZzjCeoddc6zEOv0jl8d7Cn/yJEhPSsj+9djKo+eOKvP/qNYSLvMsySpGiO8DO7jpnEgNzgeUDtl9RKn+pbS1tC1JTkAGMzi0A9EUvifaf83or/cNvaksNZzx/RRalENKOaM6FSqdra4erDtOaOGxMJKim6q6KbSGyPPp+F6BikJhNTznzPUCRsUSQ01XIf8M795ljCWesL6M3cBByoW+6iCIeWHqZWRwJYHWIShhzBppgei8+HSlrv5l0xNHC5oyAfFqkVRqbZQeeWPU22bprbNg3sQ3xpqnI8TNj3H9iDcF1wl2FseujfK4kgfapEqf7DxBcT1LON2KqauWBkbHSWzF/KJJljyqbxTS+6CZwhWn3o3UZLNwULXj4V5AhjdAyDz3Swns0Z4/8WnOt/xL4H6NHvtDFnEqQgdumUjSlhRXmjruUkS2I/x323ReXGiBZs0MYAswa78mCk+X3Samcg6X6ChUmO9SNbPAAmlhiBfW4PZ2skh2GGVgJvPQHUP/VihwrOb+ZJD+SFoOIgYsCG6uQdWFhmebaJvPpTkgIGKklfeuZjEga5s5p/i4=
    admin-user: AgAyoVglN+o+iJ9fuZrtGIJLwNomayaMSidwZFXwSBT7znJERaEK6X+tF6xWQuto3vcIzX3i1WQCtVJ5AnQ6W668JH942YqK3Q5oYJMAL7z9pcZMFmtua3WssMvmAWeGUJcXJQwf0bfPXYOyMuA8sfohUdqCbgUPuh4ukT7XLvS0a3IMSbyykV7LIBpjfmQ94Tr4pX5hEJBbxtVPgVD1EkvRlMX0x1lMBggPZZSbZdpVXbQckeidvIUVjd/y4BtyejPu2oHi1VvLDCUcBaXzkU2/zZyrtynUDt48PvkKvzh7D6t7y7v5QB6L4P4gnhJ/QyAlZl4KUfc27/VL/iFwyPMGEv0Rhe6sdNC89U4rHVBsIFMwiNlSL1fkIzc2HBjyLt74hGawCWWykT+t7uLxWJ/Zgw2iqEF+CKjz96/kFbjKtWrp494ODMrK2ZLfLsnEcjTPR06RSdym9PsLz/nZOCfS9UCOyEWe7Pnv5YeWSsS89lZLMbz+QthD945mJVQQwoBDK4f6EP8Ct5EeuUgxy8LzVzD4jalBwulz2+HDj/P4nJvicVtZqLf/J+/8MO9BVZn2nC4d6xAzr1UBd8R5vDQ6k1WQMoKhJlnhUmw5WBi0r0wBhlrl+DIPYcJXDiR8DmVG+yu3mAEviLpf8NRD/Ek7+gXtLaj6nrTEhT4w0n1n/JbrJw+tudvjXyTol6+KdI68+04hzw==
  template:
    metadata:
      name: grafana-secrets
      namespace: monitoring
