---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secrets
  namespace: monitoring
spec:
  encryptedData:
    grafana-admin-password: AgBnNeveBjczXa6DlXHp7a2IRc5MslgbwHdvxPZvf4Vc8+N+WHt5bNmTVU/n1m7RGp8DoMul9Zmmo/tjMwuHfmJ1OUdLm0fmU7IOQMOqDETBjt+0wrnsbWBGUp2Wb3CIm7372+1lFMAT5jIFptS7uRkXoXQ4guzihweGP21sAt4UBuQ2q7gmymEEOoXNZt50u0FGhH3kcoInDZ9xFHNPWHzKMC1JXHaxsRTEbroAfpRM/qK+w05OrIH2Q2zU29w/RWG2gRZ+zcADGTY6MHJTpffsyLr+sYrp956ClC4MOxM06wHy7UnXhBAp964nef40f7/RiDDk/FzKoAT6/Ea5QWK50PB5rqiQCw7U54DCTRap/1L1Rv6RM6/D9xvyyUHcGrUoMcjYvqyUblukQoAzTqJi9jSe//R15jZxBUiBMwKK/c3AoCQw3eEMWyv3splJNUkaOXrvWD+H+m3fS59m/K9lgGxjct/Bi9pNkHY8RQi80DwJ62QEY3/j1wnKFLz7LdeaXAxKaELvdka9UIgZA+o7CnZ6sP9cB1gVWjI4OhZapFqWvKxFVsI3bYfZ+GeTIbqJvahU6jMYiRS1tVMOntThYy6Z+uTz4g1LirZF9rSNLLsEF5+TUEBPWu99NctRoTpVJ4O7IyYt0ot8B2UyOZv7xnoYWXbKvz0BAJA+Sts5koS79GdE4lNCjcWshj+fYsMvk6+kbXxKi0lTbts=
  template:
    metadata:
      name: grafana-secrets
      namespace: monitoring
