---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: longhorn-metrics
  namespace: monitoring
  labels:
    app.kubernetes.io/name: longhorn
    release: prometheus
spec:
  selector:
    matchLabels:
      app: longhorn-manager
  namespaceSelector:
    matchNames:
      - longhorn-system
  endpoints:
    - port: manager
      interval: 30s
      scrapeTimeout: 10s
      path: /metrics
