apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana-community
        namespace: flux-system
      version: "18.4.4"
  valuesFrom:
    - kind: ConfigMap
      name: loki-values
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
