apiVersion: batch/v1
kind: Job
metadata:
  name: ollama-model-pull
  namespace: ai-edge
spec:
  backoffLimit: 5
  template:
    spec:
      # serviceAccountName: default
      containers:
      - name: puller
        image: ollama/ollama:0.24.0
        command:
          - sh
          - -c
          - |
            until ollama list -h ollama-service:11434 2>/dev/null; do
              echo "Waiting for Ollama service..."
              sleep 5
            done
            echo "Ollama is ready, pulling model..."
            ollama pull -h ollama-service:11434 $MODEL_NAME
        env:
        - name: MODEL_NAME
          valueFrom:
            configMapKeyRef:
              name: ollama-configmap
              key: model-name
      restartPolicy: OnFailure
