apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: ai-edge
  labels:
    app: ollama
spec:
  selector:
    app: ollama
  ports:
  - port: 11434
    protocol: TCP
    targetPort: 11434
  type: ClusterIP
