apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: linkding-network-policy
  namespace: linkding
spec:
  endpointSelector: {}
  ingress:
    - fromEntities:
        - world
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"

