apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-home-arpa
  namespace: cert-manager
spec:
  secretName: cert-home-arpa
  isCA: true
  dnsNames:
    - home.arpa
    - "*.home.arpa"
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
