apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: commafeed-pvc
  labels:
    app: commafeed
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 256Mi
