---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 30m
  timeout: 15m
  chartRef:
    kind: OCIRepository
    name: cilium
    # namespace is not required here
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
  valuesFrom:
    - kind: ConfigMap
      name: cilium-values
