crds:
  enabled: true
  keep: true

# config:
#   apiVersion: controller.config.cert-manager.io/v1alpha1
#   kind: ControllerConfiguration
#   enableGatewayAPI: true

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 20m
    memory: 128Mi
