apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - kube-prometheus-stack
  # Not suited for MicroSD/USB Flash Drive, use NVME instead
  # - alloy
  # - loki
  # - tempo
