---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: commafeed-db-secrets
  namespace: commafeed
spec:
  encryptedData:
    password: AgCLbSAPrbC5XC+pUVk8e6xr62q/vtn/Ms/gzHFGCapUcBCh4vYDPEzVCOzPWPK5z4kP+rXFMxiJtUnkEuaSXnUCJtVNEA4pyzV7PqtQumY87/SkSBZrRj356NKDkpb58RuFmHZXWmw9P8JLDQoXEN1fAhCDsO/8p7VbSnoUcWu5T4XX0WHXtnhDv4H8foI2vA3LMzgu4iGKwkfnP+gYhpMe/mIVTOXl24faJTM92j9gg93dKgKM7/F3biexE5cJ45wmDb3U/UQo+pHktSNjMT5q+S/J9GK04+jvJ2gJWExVUcSOmPygKunGkq63Z4x9MnJZ5r5cvM3hddeobwnUQDX74oWytoakr9fTjJK7sXvqFqt2SR1qfanvMEW8lueHBK9ggdJ92gJPyq06+IDXifqIjO41qRkGcl1QKV9R4se0/muNeqKIthggHHsb/wMNgB1zSA8/y58F4MIgy165uY3dMrkZuhjGybG23K+vnDF4Mfwz5MaI8OzCQEVTp5gl3RA6BD/SX8SWS6gYrUvvQm+eBEZLApQjm1ywOReZDn8jKQeV/0rToaQIxpIVVK2wtACj9/sD4RwigBBgdh7vp1JUQ/ZEn1FbnRB4dtGa4izpaP+55+92F65N2b3NP7c3O65KkOJy5Dt/nK4U2RC5zzVVqUj7WC/OFBC2Od2YE91+rdMQCl88xVDaLw8qFTxHWZsuoGbcDAik0Q==
    username: AgC+JI0ymSCPJZowMMvUXHVxrLFl9/RKh80EpcYuuHqK/oVaMjQ5Gc3rE7m5oObby7bjvDEQiY+HOc1iHZRQJfuUj9cZigbAIie+2iQzga04v11OIosfOCDeI+foEHGYQoIBkIC9+mTsK+yXLhhTLYKDSPv2Qn559Vy9/btPGGFjCdfOcwvmTcd1IK9Hi+u0vQPh2o2nH/sust4Rf5SLjBHsRiojM3uAhAXbq8ird+m2DFvtTTWynFobdzH2t+Vc4Bxgks+3B3to2qATWNvZ5gYWWPsSMziPpYdt5FfgBHXLo9qBbfH3UlCKaVA90R8Zni3ivRi1b/Ku8LXUeJ+T6jofiIAbInnHBvfJEShaPxf1x4/JN6pHpuExaHa5KB1kXwANmpPyPzhoDwjXGKfF59C8C/wa6Cb8jEn4yuzQgYnhWRid75ETNIVDb+7dF0rzjUYE/HGSjVeBs2HGTci8i/4+ifiLnStw1SrrC9Bd10fDlRKWuG3KKUPixWl/TlrfVUeTQbqGME+4X4UUyWaZeRDw90JjVGt93LAbnQURsOQw0/rWCCNwSx4RU5N+GJyF1fCH+wYIhZpBGnZKLPXXzh6wH3UIwo74SIZmmIeaPUN53BXORTBVm8f8a331NbpdoFW/YM1YEsmPTwVnmZ1w68dp++6oCNm8fbgi0hZwaL73Ou9fT4WAcxwVvp+g27lYYuC6AUVtNMG0FO4=
  template:
    metadata:
      name: commafeed-db-secrets
      namespace: commafeed
    type: kubernetes.io/basic-auth
