---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: linkding-secrets
  namespace: linkding
spec:
  encryptedData:
    LD_SUPERUSER_NAME: AgCyxpy7fLQGfH56UEM8oK1omUfsATpcbuck96nawsPfrf8ENSgppfP19SD6KftHMjhCZcIAf47QT0x0kn0CQmrVKDx8Ni39e5jEOt5kb7OsheXUkfKEUyykOqtsvP2TQ7qwuqVUXOwTjYwxT6eSGCgj+PEvcUsu/e2sUbC6jGdoIXYw6aHVYr+Av3YkLzGqAJmIHESz535i7JITVjG0pX7NwcONLsc0etgh6cI5GLDFinPnSa5zBZWdmiI1AvsOaTHrnQVXOY635ktTPEkiaEaB4gMX153IPKYvZq+ZRYfoyWUyOQ08R5RxrjPmeiSTgktwy1PKWJx04eD8Gx+TUw6koIW90qQ1R8dWLmImWkOM6rXDFfcfM2wcv7qWSao76awXihgOkfeqnJmmBelinqMioyCHTcUxi1LUXc0C9g5SV7YO99pcUOk2qGaaI3hBHDkfSYQmrUiq4dh7lqEfqt1fXbesySguFuFz1/t00OppSFEm2hh1AIFeF6ruUD3yH11r/oIYmk9idRrYtxOOLuR7HbsPELOQA0qR+XsPa8Hlnb0l6qYzdCAQ2UYcdQB7oyB8wkgblRtwhJj1jbHcYN4P4F7T7T7Gjb2v8Pf8++0F+xl2MPjXJcz3zsk0Hppv65fHchZKjEBVrIK7JrPNQcYt73w4fEXaJpJx4BfVsPJD5UvpbTjEyU3vgRXl6PxOv80gcZFZcQ==
    LD_SUPERUSER_PASSWORD: AgA4UZyA3k3hmShd0001vPC0FWvTy0Y6UUHMpxkZWAAlGuMl7CTmLMEJXf9wCev76AyW/pf0q48e/4uMZeLsduDNx5bUZoeHcVrHOXcNp1kFk2gxHxmNt2afd9fpT/JnohoS+zdR0JpX6sUHNIfG0Y2ABNPZiucxep5bA4GlO/WEd8koUysRRB/SuDXo79bMd5Lgiw92No8ArMTEw6otDPmK8fQ5+SKKUImLAJ4/ezdBsPElpJhTXM/KIdh+rrhG8OxI/sluSWiSkmVslRZ4H0Jp1tS8agUHubzjI7yH16TTQPTAx9o7G9nR++DDlmcJYeOtrMKDDJv+3LHKzX4r9R25GP8QlV93CJO5hkYxQAj6KsJqChJHfg1ARDAMLEc6YSow38WQOtjS0aJOpfUe5S6vxOUQpkltjGZn+gx0oB9RgYrp5LmicAMl+ZXspNFtoTPSAdVdTQIZZx3o2OKA0JTvAKquRbvKXSA1VIKxH6LWfTNeY1Pvbo7BWw10+wgBRUPOP/QYdDq90LzIytdAGvryQ7bKf0+yHIXMT1bvEkawYxmST7W+0/dN4FHSWN4LJncZTqsa9f+NLfIgHKk0LKFWelwwQ7NUQSALh/HPdzXPxQiqAWUOzam9IIKa8Y5PQMkPst+InsSQfcotiZdiCPpiaRe993Il2NTcJAtwXyDizWRrjwoamVidwyn7Nwvs7FsFkNUmd0qITw==
  template:
    metadata:
      name: linkding-secrets
      namespace: linkding
