apiVersion: v1
kind: ConfigMap
metadata:
  name: commafeed-configmap
data:
  COMMAFEED_USERS_ALLOW_REGISTRATIONS: "true"
  COMMAFEED_USERS_MINIMUM_PASSWORD_LENGTH: "12"
  COMMAFEED_USERS_EMAIL_ADDRESS_REQUIRED: "true"
  QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://postgres.commafeed.svc.cluster.local:5432/commafeed"
